#!/usr/bin/env python3
"""WAF/CDN/防火墙检测 — 通过响应特征识别 Web 防护"""
import sys
import io
if sys.stdout.encoding != "utf-8":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
import urllib.request
import urllib.error
import ssl
import json
import re

ssl_ctx = ssl.create_default_context()
ssl_ctx.check_hostname = False
ssl_ctx.verify_mode = ssl.CERT_NONE

# WAF/CDN 指纹特征库
WAF_FINGERPRINTS = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "__cfduid", "cf-request-id"],
        "server": ["cloudflare"],
        "cookies": ["__cfduid", "cf_clearance", "__cf_bm"],
        "response": [],
        "status_codes": [],
    },
    "AWS CloudFront": {
        "headers": ["x-cache", "x-amz-cf-id", "x-amz-cf-pop"],
        "server": ["cloudfront"],
        "cookies": [],
        "response": [],
        "status_codes": [],
    },
    "Akamai": {
        "headers": ["x-akamai-transformed", "x-akamai-request-id", "x-akamai-session-info"],
        "server": ["akamai", "akamaighost"],
        "cookies": ["ak_bmsc"],
        "response": [],
        "status_codes": [403, 503],
    },
    "Imperva / Incapsula": {
        "headers": ["x-iinfo", "x-cdn", "x-request-info"],
        "server": ["incapsula"],
        "cookies": ["visid_incap_", "incap_ses_", "nlbi_"],
        "response": [],
        "status_codes": [],
    },
    "F5 BIG-IP": {
        "headers": ["x-wa-info", "x-cnection"],
        "server": ["big-ip", "bigip"],
        "cookies": ["bigipserver", "bigipserverpool", "ts", "f5_cspm", "f5_st"],
        "response": [],
        "status_codes": [],
    },
    "Fortinet FortiWeb": {
        "headers": ["x-fortigate"],
        "server": ["fortiweb", "fortigate"],
        "cookies": ["fortiwafsid"],
        "response": [],
        "status_codes": [],
    },
    "Barracuda WAF": {
        "headers": ["x-barracuda"],
        "server": ["barracuda"],
        "cookies": ["barra_counter_session", "bniproxy"],
        "response": [],
        "status_codes": [],
    },
    "Citrix NetScaler": {
        "headers": ["x-ns"],
        "server": ["netscaler", "citrix"],
        "cookies": ["ns_af", "citrix_ns_id", "nsc_"],
        "response": [],
        "status_codes": [],
    },
    "阿里云 WAF (Alibaba / Aliyun)": {
        "headers": ["x-backend-lb", "x-aliyun", "eagleeye-traceid"],
        "server": ["aliyun", "alibaba", "tengine"],
        "cookies": ["aliyungf_tc"],
        "response": [],
        "status_codes": [],
    },
    "腾讯云 WAF": {
        "headers": ["x-tencent", "x-nws-log-uuid"],
        "server": ["tencent", "stgw"],
        "cookies": [],
        "response": [],
        "status_codes": [],
    },
    "百度云加速 / 百度 WAF": {
        "headers": ["x-bce-", "yunjiasu"],
        "server": ["yunjiasu", "bce"],
        "cookies": ["yjs_id"],
        "response": [],
        "status_codes": [],
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "server": ["sucuri", "cloudproxy"],
        "cookies": ["sucuric_session", "sucuri_cloudproxy_uuid"],
        "response": [],
        "status_codes": [],
    },
    "Wordfence (WordPress WAF)": {
        "headers": ["x-wf-"],
        "server": [],
        "cookies": [],
        "response": ["Generated by Wordfence"],
        "status_codes": [503],
    },
    "ModSecurity": {
        "headers": [],
        "server": ["mod_security"],
        "cookies": [],
        "response": ["ModSecurity", "This error was generated by Mod_Security"],
        "status_codes": [403, 406],
    },
    "Wallarm": {
        "headers": ["x-wallarm"],
        "server": ["wallarm"],
        "cookies": [],
        "response": [],
        "status_codes": [],
    },
    "StackPath / MaxCDN": {
        "headers": ["x-stackpath", "x-proxy-cache"],
        "server": ["stackpath"],
        "cookies": [],
        "response": [],
        "status_codes": [],
    },
    "Fastly": {
        "headers": ["x-served-by", "x-cache-hits", "x-timer", "fastly-"],
        "server": ["fastly", "varnish"],
        "cookies": [],
        "response": [],
        "status_codes": [],
    },
    "Varnish": {
        "headers": ["x-varnish", "via"],
        "server": ["varnish"],
        "cookies": [],
        "response": [],
        "status_codes": [],
    },
    "HAProxy": {
        "headers": [],
        "server": ["haproxy"],
        "cookies": [],
        "response": [],
        "status_codes": [],
    },
    "NGINX": {
        "headers": [],
        "server": ["nginx"],
        "cookies": [],
        "response": [],
        "status_codes": [],
    },
    "Apache": {
        "headers": [],
        "server": ["apache", "apache/2"],
        "cookies": [],
        "response": [],
        "status_codes": [],
    },
    "Vercel": {
        "headers": ["x-vercel-id", "x-vercel-cache", "x-vercel-ip-country"],
        "server": ["vercel", "now"],
        "cookies": [],
        "response": [],
        "status_codes": [],
    },
    "Netlify": {
        "headers": ["x-nf-request-id"],
        "server": ["netlify"],
        "cookies": [],
        "response": [],
        "status_codes": [],
    },
    "Heroku": {
        "headers": ["x-heroku-"],
        "server": [],
        "cookies": [],
        "response": [],
        "status_codes": [],
    },
}


def detect_waf(url, timeout=10):
    """检测目标是否使用 WAF/CDN"""
    result = {
        'url': url,
        'waf_detected': [],
        'cdn_detected': [],
        'server_info': {},
        'is_behind_cdn': False,
        'is_behind_waf': False,
    }

    try:
        req = urllib.request.Request(url, headers={
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        })
        resp = urllib.request.urlopen(req, timeout=timeout, context=ssl_ctx)

        resp_headers = {k.lower(): v for k, v in resp.headers.items()}
        # 读取部分响应体
        resp_body = resp.read(16384).decode('utf-8', errors='ignore')
        status_code = resp.status

        # 检查每个指纹
        for waf_name, fingerprint in WAF_FINGERPRINTS.items():
            matched = False
            evidence = []

            # 检查响应头
            for header_pattern in fingerprint['headers']:
                for resp_header_key, resp_header_value in resp_headers.items():
                    if header_pattern.lower() in resp_header_key.lower():
                        evidence.append(f"Header: {resp_header_key}={resp_header_value}")
                        matched = True

            # 检查 Server 头
            server = resp_headers.get('server', '')
            for server_pattern in fingerprint['server']:
                if server_pattern.lower() in server.lower():
                    evidence.append(f"Server: {server}")
                    matched = True

            # 检查 Cookies
            set_cookie = resp_headers.get('set-cookie', '')
            for cookie_pattern in fingerprint['cookies']:
                if cookie_pattern.lower() in set_cookie.lower():
                    evidence.append(f"Cookie contains: {cookie_pattern}")
                    matched = True

            # 检查响应体
            for resp_pattern in fingerprint['response']:
                if resp_pattern.lower() in resp_body.lower():
                    evidence.append(f"Body contains: {resp_pattern}")
                    matched = True

            # 检查状态码
            if status_code in fingerprint['status_codes']:
                evidence.append(f"Status code: {status_code}")

            if matched or (evidence and status_code in fingerprint['status_codes']):
                result['waf_detected'].append({
                    'name': waf_name,
                    'evidence': evidence,
                })
                matched = True

        # 判定
        result['server_info']['server'] = resp_headers.get('server', '')
        result['server_info']['x_powered_by'] = resp_headers.get('x-powered-by', '')
        result['server_info']['status_code'] = status_code

        # CDN 判定
        cdn_names = ['Cloudflare', 'AWS CloudFront', 'Akamai', 'Fastly', 'StackPath / MaxCDN', 'Vercel', 'Netlify']
        for w in result['waf_detected']:
            if w['name'] in cdn_names:
                result['cdn_detected'].append(w['name'])
                result['is_behind_cdn'] = True

        if result['waf_detected']:
            non_cdn = [w for w in result['waf_detected'] if w['name'] not in cdn_names]
            if non_cdn or any(w['name'] not in cdn_names for w in result['waf_detected']):
                result['is_behind_waf'] = True

    except urllib.error.HTTPError as e:
        result['server_info']['status_code'] = e.code
        result['server_info']['error'] = f"HTTP {e.code}"
    except Exception as e:
        result['server_info']['error'] = str(e)

    return result


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 waf_detect.py <url> [<url2> ...]")
        sys.exit(1)

    for arg in sys.argv[1:]:
        url = f"https://{arg}" if not arg.startswith('http') else arg
        result = detect_waf(url)

        print(f"\n{'='*60}")
        print(f"🛡️  WAF/CDN 检测: {url}")
        print(f"{'='*60}")

        if result.get('server_info', {}).get('error'):
            print(f"   ❌ 请求失败: {result['server_info']['error']}")
            continue

        print(f"   状态码: {result['server_info'].get('status_code')}")
        server = result['server_info'].get('server', '')
        if server:
            print(f"   Server: {server}")

        if result['waf_detected']:
            print(f"\n   🔴 检测到防护措施 ({len(result['waf_detected'])}):")
            for w in result['waf_detected']:
                print(f"      {w['name']}:")
                for e in w['evidence']:
                    print(f"         • {e}")
        else:
            print(f"\n   🟢 未检测到常见 WAF/CDN")

        if result['is_behind_cdn']:
            print(f"\n   ⚠️  目标使用 CDN: {', '.join(result['cdn_detected'])}")
            print(f"      提示: IP 扫描可能命中 CDN 节点而非真实服务器")

        print(f"\n   📄 JSON:\n{json.dumps(result, indent=2, ensure_ascii=False)}")


if __name__ == '__main__':
    main()
